<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NET30 Ponto</title><style>
:root{font-family:Inter,Arial,sans-serif;color:#111827;background:#f4f7f5}*{box-sizing:border-box}body{margin:0;background:#f4f7f5}.app{min-height:100vh}.top{background:#07140e;color:white;padding:18px 22px;display:flex;justify-content:space-between;align-items:center}.brand{font-weight:800;font-size:22px}.muted{color:#9ca3af;font-size:12px}.wrap{max-width:1050px;margin:auto;padding:22px}.grid{display:grid;grid-template-columns:1fr 1.5fr;gap:18px}.card{background:white;border:1px solid #e5e7eb;border-radius:16px;padding:20px;box-shadow:0 5px 20px #00000008}.h{font-size:17px;font-weight:800;margin:0 0 14px}.clock{text-align:center;font-size:38px;font-weight:800;margin:12px 0}.status{text-align:center;padding:9px;border-radius:10px;background:#ecfdf5;color:#047857;font-weight:700;margin-bottom:14px}.btn{width:100%;border:0;border-radius:13px;padding:15px;font-size:16px;font-weight:800;cursor:pointer;background:#16a34a;color:white}.btn:disabled{opacity:.55}.btn.secondary{background:#111827;margin-top:9px}.row{display:flex;gap:10px;flex-wrap:wrap}.stat{flex:1;min-width:120px;background:#f8fafc;padding:14px;border-radius:12px}.stat b{font-size:22px;display:block}.table{width:100%;border-collapse:collapse;font-size:13px}.table th,.table td{padding:10px 7px;border-bottom:1px solid #eee;text-align:left}.pill{padding:4px 8px;border-radius:99px;background:#dcfce7;color:#166534;font-size:11px;font-weight:700}.danger{background:#fee2e2;color:#991b1b}.empty{text-align:center;color:#6b7280;padding:30px}.map{height:180px;border-radius:12px;background:linear-gradient(135deg,#dbeafe,#dcfce7);display:flex;align-items:center;justify-content:center;color:#14532d;text-align:center}.small{font-size:12px;color:#6b7280;line-height:1.5}.install{margin-top:12px;background:#f0fdf4;border:1px solid #bbf7d0;padding:12px;border-radius:12px}@media(max-width:780px){.grid{grid-template-columns:1fr}.wrap{padding:12px}.top{padding:15px}}
</style></head><body><div class="app"><header class="top"><div><div class="brand">NET30 PONTO</div><div class="muted">Controle de ponto com localização</div></div><div id="net">● verificando conexão...</div></header><main class="wrap"><div class="grid"><section><div class="card"><h2 class="h">Registrar ponto</h2><div class="clock" id="clock">--:--:--</div><div class="status" id="gps">Localização: aguardando</div><button class="btn" id="punch">BATER PONTO</button><button class="btn secondary" id="clear">Limpar registros deste aparelho</button><div class="install"><b>💾 Salvo automaticamente</b><div class="small">Os registros ficam armazenados neste aparelho. Se estiver sem internet, continuam disponíveis e podem ser sincronizados com um servidor na próxima versão.</div></div></div></section><section><div class="card"><h2 class="h">Resumo</h2><div class="row"><div class="stat"><span class="small">Hoje</span><b id="today">0</b></div><div class="stat"><span class="small">Total</span><b id="total">0</b></div><div class="stat"><span class="small">Último</span><b id="last">--:--</b></div></div><h2 class="h" style="margin-top:22px">Histórico</h2><div id="history"></div></div></section></div></main></div><script>
const KEY='net30_pontos_v1'; let records=JSON.parse(localStorage.getItem(KEY)||'[]');
function save(){localStorage.setItem(KEY,JSON.stringify(records));render()}
function now(){return new Date()}
function fmt(d){return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'medium'}).format(d)}
function render(){const today=new Date().toDateString();const rToday=records.filter(r=>new Date(r.ts).toDateString()===today);document.querySelector('#today').textContent=rToday.length;document.querySelector('#total').textContent=records.length;document.querySelector('#last').textContent=records.length?new Intl.DateTimeFormat('pt-BR',{timeStyle:'short'}).format(new Date(records[0].ts)):'--:--';const h=document.querySelector('#history');if(!records.length){h.innerHTML='<div class="empty">Nenhum ponto registrado ainda.</div>';return}h.innerHTML='<table class="table"><thead><tr><th>Data/hora</th><th>Localização</th><th>Conexão</th></tr></thead><tbody>'+records.slice(0,30).map(r=>`<tr><td>${fmt(new Date(r.ts))}</td><td>${r.lat!=null&&r.lng!=null?`${Number(r.lat).toFixed(6)}, ${Number(r.lng).toFixed(6)}<br><small>Precisão: ~${Math.round(r.accuracy||0)} m</small>`:'Não obtida'}</td><td><span class="pill">${r.online?'Online':'Offline'}</span></td></tr>`).join('')+'</tbody></table>'}
function updateNet(){document.querySelector('#net').textContent=navigator.onLine?'● online':'● offline';document.querySelector('#net').style.color=navigator.onLine?'#86efac':'#fca5a5'}
function clock(){document.querySelector('#clock').textContent=new Intl.DateTimeFormat('pt-BR',{timeStyle:'medium'}).format(now())}setInterval(clock,1000);clock();updateNet();addEventListener('online',updateNet);addEventListener('offline',updateNet);render();
function gpsError(e){const map={1:'Permissão de localização negada. Autorize a localização no navegador.',2:'Não foi possível determinar sua localização. Verifique o GPS.',3:'O GPS demorou demais para responder. Tente novamente em um local aberto.'};return map[e.code]||'Não foi possível obter a localização.'}
async function locate(){
 if(!('geolocation' in navigator)) throw new Error('Este navegador não oferece localização.');
 if(!window.isSecureContext && location.protocol!=='file:') throw new Error('A localização exige uma conexão segura (HTTPS).');
 if(navigator.permissions?.query){try{const q=await navigator.permissions.query({name:'geolocation'});if(q.state==='denied')throw new Error('Permissão de localização bloqueada. Libere a localização nas configurações do navegador.')}catch(e){if(e.message.includes('Permissão'))throw e}}
 return new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(
 p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy}),
 e=>reject(new Error(gpsError(e))),
 {enableHighAccuracy:true,timeout:20000,maximumAge:0}
 ));
}
document.querySelector('#punch').onclick=async()=>{const b=document.querySelector('#punch'),gps=document.querySelector('#gps');b.disabled=true;b.textContent='OBTENDO LOCALIZAÇÃO...';gps.textContent='Solicitando permissão do GPS...';try{const p=await locate();const rec={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),ts:new Date().toISOString(),lat:p.lat,lng:p.lng,accuracy:p.accuracy,online:navigator.onLine};records.unshift(rec);save();gps.textContent=`✓ Localização registrada • precisão ~${Math.round(p.accuracy)} m`;b.textContent='PONTO REGISTRADO ✓'}catch(e){gps.textContent='⚠ '+e.message;b.textContent='TENTAR NOVAMENTE';}finally{setTimeout(()=>{b.disabled=false;b.textContent='BATER PONTO'},1800)}};
document.querySelector('#clear').onclick=()=>{if(confirm('Apagar todos os registros deste aparelho?')){records=[];save();document.querySelector('#gps').textContent='Localização: aguardando'}};
</script></body></html>
